### ISSUE TITLE
Error when running the script

### ISSUE THREAD

**Issue by IkerAlus** [bee344/evm-tests#6]
After I installed all the required dependencies, I get the following error when running the script as stated in the Readme:

```
Compiled 95 Solidity files successfully (evm target: paris).
You're running a network fork starting from the latest block.
Performance may degrade due to fetching data from the network with each run.
If connecting to an archival node (e.g. Alchemy), we strongly recommend setting
blockNumber to a fixed value to increase performance with a local cache.
An unexpected error occurred:

Error: Cannot find module 'chai-subset'
Require stack:
- /Users/ikeralustiza/Documents/evm_test_suite/evm-tests/matter-labs-tests/test/MatterLabsTests.ts
- /Users/ikeralustiza/Documents/evm_test_suite/evm-tests/node_modules/mocha/lib/mocha.js
- /Users/ikeralustiza/Documents/evm_test_suite/evm-tests/node_modules/mocha/index.js
- /Users/ikeralustiza/Documents/evm_test_suite/evm-tests/node_modules/hardhat/builtin-tasks/test.js
- /Users/ikeralustiza/Documents/evm_test_suite/evm-tests/node_modules/hardhat/internal/core/tasks/builtin-tasks.js
- /Users/ikeralustiza/Documents/evm_test_suite/evm-tests/node_modules/hardhat/internal/core/config/config-loading.js
- /Users/ikeralustiza/Documents/evm_test_suite/evm-tests/node_modules/hardhat/internal/cli/cli.js
- /Users/ikeralustiza/Documents/evm_test_suite/evm-tests/node_modules/hardhat/internal/cli/bootstrap.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (/Users/ikeralustiza/Documents/evm_test_suite/evm-tests/node_modules/@cspotcode/source-map-support/source-map-support.js:811:30)
    at Function.Module._load (node:internal/modules/cjs/loader:985:27)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (/Users/ikeralustiza/Documents/evm_test_suite/evm-tests/matter-labs-tests/test/MatterLabsTests.ts:6:1)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module.m._compile (/Users/ikeralustiza/Documents/evm_test_suite/evm-tests/node_modules/ts-node/src/index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/ikeralustiza/Documents/evm_test_suite/evm-tests/node_modules/ts-node/src/index.ts:1621:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/ikeralustiza/Documents/evm_test_suite/evm-tests/matter-labs-tests/test/MatterLabsTests.ts',
    '/Users/ikeralustiza/Documents/evm_test_suite/evm-tests/node_modules/mocha/lib/mocha.js',
    '/Users/ikeralustiza/Documents/evm_test_suite/evm-tests/node_modules/mocha/index.js',
    '/Users/ikeralustiza/Documents/evm_test_suite/evm-tests/node_modules/hardhat/builtin-tasks/test.js',
    '/Users/ikeralustiza/Documents/evm_test_suite/evm-tests/node_modules/hardhat/internal/core/tasks/builtin-tasks.js',
    '/Users/ikeralustiza/Documents/evm_test_suite/evm-tests/node_modules/hardhat/internal/core/config/config-loading.js',
    '/Users/ikeralustiza/Documents/evm_test_suite/evm-tests/node_modules/hardhat/internal/cli/cli.js',
    '/Users/ikeralustiza/Documents/evm_test_suite/evm-tests/node_modules/hardhat/internal/cli/bootstrap.js'
  ]
}
```

**Comment by IkerAlus** [comment]
Adding the package manually solved the issue:

` yarn add chai-subset`

**Comment by IkerAlus** [comment]
Adding the package manually solved the issue:

` yarn add chai-subset`
